name: CI

# List of events to triggers this workflows edit cOmment
on:
  push:
  pull_request:

# Define jobs that can run sequentially or in parallel
jobs:

  # Job name
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    # Sequence of tasks that will be executed
    steps:

        # Debug message
      - name: Run a debug message
        run: echo "::debug::Here is your debug message"
        
        # # Error
      - name: Run an error
        run: echo "::error file=main.tsx, line=10::Missing semicolon"

      - name: "Run a script"
        run: ./scripts/sample.ps1

      # Runs a single command
      - name: Run a one-line script
        run: echo "Hello, world!"

      # Runs a set of commands
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
